name: posts_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  api_client:
    path: ../api_client
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: 9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
